"""add patient_notes table

Revision ID: 26edc9132ab0
Revises: 
Create Date: 2025-07-11 16:17:02.531080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.core.security import EncryptedText, EncryptedString


# revision identifiers, used by Alembic.
revision: str = '26edc9132ab0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_patients_name_search'), 'patients', ['name_search'], unique=False)
    op.alter_column('therapy_sessions', 'results',
               existing_type=sa.VARCHAR(),
               type_=EncryptedText(),
               existing_nullable=False)
    op.drop_index(op.f('ix_clinics_email'), table_name='users')
    op.drop_index(op.f('ix_clinics_id'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_clinics_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_clinics_email'), 'users', ['email'], unique=True)
    op.alter_column('therapy_sessions', 'results',
               existing_type=EncryptedText(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_index(op.f('ix_patients_name_search'), table_name='patients')
    # ### end Alembic commands ###
